name: CI/CD

on: 
  push:
    branches:
      - main
    tags: 
      - "v*"
  pull_request:
    branches:
      - main

jobs:
  code-quality:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: install black
        run: python -m pip install black
      - name: install isort
        run: python -m pip install isort 
      - name: install ruff
        run: python -m pip install ruff black
      - name: Run black
        run: python -m black --check .
      - name: Run isort
        run: python -m isort --check .
      - name: Run ruff
        run: python -m ruff check .

  deploy-to-production:
    needs: code-quality
    runs-on: ubuntu-latest
    if: startsWith(github.event.ref, 'refs/tags/v')
    steps:
    - name: Execute remote SSH commands using SSH KEY
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        port: ${{ secrets.SERVER_PORT }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
        script: |
          cd ~/hillel_support_24
          git pull
          docker compose build
          docker compose down
          docker compose up -d

          docker compose exec api python support/manage.py migrate

          echo "Deployment successfull"